

allvars <- function(){
  c(
    "01_indications_and_usage",
    "01_purpose",
    "01_purpose_table",
    "02_dosage_and_administration",
    "03_active_ingredient",
    "03_dosage_forms_and_strengths",
    "03_inactive_ingredient",
    "03_spl_product_data_elements",
    "04_boxed_warning",
    "04_contraindications",
    "04_general_precautions",
    "04_user_safety_warnings",
    "05_laboratory_tests",
    "05_precautions",
    "05_warnings",
    "05_warnings_and_cautions",
    "05_when_using",
    "06_adverse_reactions",
    "07_drug_and_or_laboratory_test_interactions",
    "07_drug_interactions",
    "08_geriatric_use",
    "08_labor_and_delivery",
    "08_nonteratogenic_effects",
    "08_nursing_mothers",
    "08_pediatric_use",
    "08_pregnancy",
    "08_pregnancy_or_breast_feeding",
    "08_teratogenic_effects",
    "08_use_in_specific_populations",
    "09_abuse",
    "09_controlled_substance",
    "09_dependence",
    "09_drug_abuse_and_dependence",
    "10_overdosage",
    "11_description",
    "12_clinical_pharmacology",
    "12_mechanism_of_action",
    "12_microbiology",
    "12_pharmacodynamics",
    "12_pharmacogenomics",
    "12_pharmacokinetics",
    "13_animal_pharmacology_and_or_toxicology",
    "13_carcinogenesis_and_mutagenesis_and_impairment_of_fertility",
    "13_nonclinical_toxicology",
    "14_clinical_studies",
    "15_references",
    "16_disposal_and_waste_handling",
    "16_how_supplied",
    "16_safe_handling_warning",
    "16_storage_and_handling",
    "17_ask_doctor",
    "17_ask_doctor_or_pharmacist",
    "17_do_not_use",
    "17_information_for_owners_or_caregivers",
    "17_information_for_patients",
    "17_instructions_for_use",
    "17_keep_out_of_reach_of_children",
    "17_other_safety_information",
    "17_patient_medication_information",
    "17_questions",
    "17_spl_medguide",
    "17_spl_patient_package_insert",
    "17_stop_use",
    "xx_calibration_instructions",
    "xx_components",
    "sp_effective_time",
    "sp_id",
    "xx_intended_use_of_the_device",
    "xx_package_label_principal_display_panel",
    "sp_recent_major_changes",
    "sp_set_id",
    "xx_spl_unclassified_section",
    "xx_statement_of_identity",
    "sp_version",
    "xx_veterinary_indications",
    'of_unii',
    'of_spl_id',
    'of_product_ndc',
    'of_substance_name',
    'of_rxcui',
    'of_spl_set_id',
    'of_product_type',
    'of_pharm_class_cs',
    'of_manufacturer_name',
    'of_brand_name',
    'of_pharm_class_pe',
    'of_route',
    'of_nui',
    'of_pharm_class_moa',
    'of_package_ndc',
    'of_pharm_class_epc',
    'of_generic_name',
    'of_application_number',
    'of_dosage_form',
    'of_is_original_packager'
  )
}
tabnames <- c(
            "Overview",
            "Meta Data",  
            "ID and version", 
            "1. Indications, usage, and 2,3.dosage",
            "4., 5. Warnings and precautions", 
            "6. Adverse effects and 7. interactions",  
            "8. Special populations", 
            "10. Abuse and 9. overdosage", 
            "12. Clinical pharmacology",
            "13. Nonclinical toxicology", 
            "14. Clinical Studies and 15. References",
            "16. Supply, storage, and handling", 
            "Patient information",
            "Other",
            "OpenFDA", 
            "Other Apps", 
            'Data Reference',
            'About',
            'Download Section'
              )

# tabnames <- c(
#   overview="Overview",
#   meta="Meta Data",  
#   id="ID and version", 
#   one="1. Indications, usage, and 2,3.dosage",
#   four="4., 5. Warnings and precautions", 
#   six="6. Adverse effects and 7. interactions",  
#   eight="8. Special populations", 
#   ten="10. Abuse and 9. overdosage", 
#   twelve="12. Clinical pharmacology",
#   thirtenn="13. Nonclinical toxicology", 
#   fourteen="14. Clinical Studies and 15. References",
#   sixteen="16. Supply, storage, and handling", 
#   patient="Patient information",
#   other="Other",
#   openfda="OpenFDA", 
#   apps="Other Apps", 
#   data='Data Reference',
#   about='About',
#   'Download Section' = 'downloads'
# )

varprefixes <- list( 
  overview="Overview",
  meta="Meta Data",  
  id="ID and version", 
  one=c( '01', '02','03' ),
  four=c('04', '05'), 
  six=c('06', '07'),  
  eight=c('08', '19'), 
  nine=c('09', '10'), 
  twelve="12",
  thirteen="13", 
  fourteen=c("14", "15"),
  sixteen="16", 
  patient="17",
  other= '',
  openfda="of"
)