

allvars <- function(){
  c(
    'of_unii',
    'o2_spl_id',
    'o2_product_ndc',
    'of_substance_name',
    'o2_rxcui',
    'o2_spl_set_id',
    'of_product_type',
    'of_pharm_class_cs',
    'o2_manufacturer_name',
    'of_brand_name',
    'of_pharm_class_pe',
    'of_route',
    'of_nui',
    'of_pharm_class_moa',
    'o2_package_ndc',
    'of_pharm_class_epc',
    'of_generic_name',
    'of_application_number',
    'rh_safetyreportid',
    'pt_patientonsetage',
    'pt_patientonsetageunit',
    "pt_patientagegroup",
    "pt_patientweight",
    'pt_patientsex',
    'p2_narrativeincludeclinical',
    
    'dr_drugstartdateformat',
    'dr_drugindication',
    'dr_drugintervaldosageunitnumb',
    'dr_drugadministrationroute',
    'dr_drugdosageform',
    'dr_drugstartdate',
    'dr_drugauthorizationnumb',
    'dr_drugstructuredosageunit',
    'dr_medicinalproduct',
    'dr_drugcharacterization',
    'dr_drugstructuredosagenumb',
    'dr_drugintervaldosagedefinition',
    'dr_drugdosagetext',
    'dr_drugseparatedosagenumb',
    'dr_actiondrug',
    'dr_drugbatchnumb',
    'dr_drugenddateformat',
    'dr_drugenddate',
    'dr_drugcumulativedosageunit',
    'dr_drugcumulativedosagenumb',
    'dr_drugrecurreadministration',
    'dr_drugrecurrence',
    
    'as_activesubstance.activesubstancename', 
    "se_serious",
    "se_seriousnesscongenitalanomali",
    "se_seriousnessdeath",
    "se_seriousnessdisabling",
    "se_seriousnesshospitalization",
    "se_seriousnesslifethreatening",
    "se_seriousnessother",
    'rh_reporttype',
    'rh_safetyreportversion',
    'rh_receivedateformat',
#    'rh_primarysource',
    'rh_transmissiondateformat',
    'rh_fulfillexpeditecriteria',
    'rh_safetyreportid',
#    'rh_reportduplicate',
    'rh_receiptdate',
    'rh_receiptdateformat',
#    'rh_receiver',
    'rh_companynumb',
    'rh_occurcountry',
    'rh_duplicate',
#    'rh_sender',
    'rh_receivedate',
    'rh_transmissiondate',
    'rh_primarysourcecountry',
    'na_summary.narrativeincludeclinical',
    're_reactionoutcome',
    're_reactionmeddraversionpt',
    're_reactionmeddrapt'
  )
}

